[package]
name = "claim-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
reqwest = { version = "0.12.15", features = ["blocking", "json"] }
serde = "1.0.219"
solana-client = "2.2.6"
solana-sdk = "2.2.2"
